name = "ChunkedJSONL"
uuid = "f218240f-9760-4928-9282-fb77ffd82776"
authors = ["Tomáš Drvoštěp <tomas.drvostep@gmail.com>"]
version = "0.1.0"

[deps]
ChunkedBase = "a380dd43-0ebf-4429-88d6-6f06ea920732"
CodecZlibNG = "642d12eb-acb5-4437-bcfc-a25e07ad685c"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
ScanByte = "7b38b023-a4d7-4c5e-8d43-3f3097f304eb"
SentinelArrays = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Logging", "Test"]
